### ISSUE TITLE
Curator guidelines in BIII.eu - and its relation with EDAM-bioimaging Topic

### ISSUE THREAD

**Issue by Leandroscholz** [edamontology/edam-bioimaging#12]
Dear @matuskalas and team, 

While writing curator guidelines to BIII.eu, I stumbled upon a curious guideline from biotools and I wanted to know your opinion about it. 

In [biotools Docs, curator guidelines in Topic](https://biotools.readthedocs.io/en/latest/curators_guide.html#attribute-guidelines) it says: 

> **1. MUST** specify the single most important and relevant scientific topic

AND

> **3. SHOULD NOT** exhaustively specify all the topics of lower or secondary relevance

Well, the approach some taggers took in BIII.eu, including myself, was to add more than one Topic to the entry. For example if I knew a tool was developed and tested for a specific type of imaging modality, say, _fluorescence microscopy_, I would add it as a Topic. In addition, I would also add _Machine Learning_ if I knew the tool used such a technique to solve the problem.  

If we took the same guideline, we would rather choose _Machine Learning_ (or _fluorescence microscopy_) the single most important relevant scientific topic. My whole point is: I would like to know the long term effect of adding two or more topics, even if the second (and following) might not be the most relevant. 

I would assume that, by adding another Topic that is related to it it would make it easier for someone to find (may someone with a microscopy background would try to find tools that relate to a certain imaging technique rather than other type of topic). On the other hand, if taggers add too many Topics of secondary relevance, the search result could be cluttered with useless tools and would make it difficult. 

So, what would be better? should we follow the same guideline as biotools or just recommend that at least one topic is added and not much more than that (2-3)? 

Cheers, 
See you soon in the next taggathon.

**Comment by joncison** [comment]
Hi @Leandroscholz .... I'm the guy who wrote the _bio.tools_ guidelines.

More than one topic is fine.  I need to clarify the guideline perhaps.  The intention is that you _must_ identify the single most important topic, but can add more (and as many) as you think are highly relevant.   But avoid adding very many topics of peripheral importance.  

Does that help?

**Comment by Leandroscholz** [comment]
Hi @joncison, sorry that I haven't quoted you in the first time. Thanks for the reply! 

So really, in the BIII.eu guidelines as in biotools, we must stress to curators not to add topics of peripheral importance. I guess I overreacted with the the statement number 1 and thought it to be a strict enforcement to keep it to one single Topic. 

I guess that closes it, but out of curiosity: Is biotools succeeding in this regard (keeping only the most important topics)?

**Comment by matuskalas** [comment]
I agree with @joncison:
 1. One or more relevant Topics
 2. Not Topics of peripheral importance (or only for marketing)

This is however not what the current bio.tools guidelines say, so they need a bit of refinement.

To 2. I would add something in the sense of: Include Topic(s) that are including the tool into the pool of tools with the same Topic; plus those FEW Topics that are distinguishing the tool from the others in the pool

**Comment by joncison** [comment]
Yup ... just tell people to stick to the most important topics.  Five or less, say, not dozens.  

Generally, yes _bio.tools_ is managing this, but we don't yet formally monitor / have metrics yet.  And the topics need cleaning up, for sure, because sometimes they're redundant, *e.g.* having both _Nucleic acids_ and _DNA_ would be daft.

**Comment by Leandroscholz** [comment]
Thanks guys, I'll leave the issue open for a few more days in case there are some new comments and I will close it during the Taggathon (in the next few days).
