### ISSUE TITLE
Rename CONTRIBUTING to CONTRIBUTING.md

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edam-bioimaging#25]
I guess this need a fork, clone, rename (by `git mv`, or is there a better way?), then creating a pull request.

**Comment by ZM202** [comment]
@matuskalas I would like to give this a try. Could you pls let me know when you need it to be done by? Thanks.

**Comment by ZM202** [comment]
All set, could you please check the PR requested. Thanks.

**Comment by matuskalas** [comment]
Fixed by #26
