### ISSUE TITLE
Update NCBO BioPortal links to include ?p=classes

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edam-bioimaging#27]
I think it'll be great to update most of the links to browsing EDAM in the NCBO BioPortal from https://bioportal.bioontology.org/ontologies/EDAM-BIOIMAGING to https://bioportal.bioontology.org/ontologies/EDAM-BIOIMAGING?p=classes. In most of the places, it makes sense to point to **browsing** (_i.e._ the "Classes" tab, `?p=classes`), instead of the default "Summary" tab.

Way forward: Search for all links to https://bioportal.bioontology.org, and update everywhere where it'll be better with the "Classes" tab.

(A good short mini-task for newcomers! 😉 incl. Outreachy applicants)

**Comment by Lukong123** [comment]
Hello @matuskalas i will like to work on this

**Comment by Lukong123** [comment]
Please I am a little bit confuse can you throw more light to it, where do we search all the links?

**Comment by matuskalas** [comment]
> Please I am a little bit confuse can you throw more light to it, where do we search all the links?

Sure! Please search for _e.g._ `bioportal.bioontology.org` in the GitHub search box up left (the default option 'In this repository'). I can see that all the hits are as they should be, so nothing more to improve here in this repo, sorry😅 Please do the same check in edamontology/edamontology#665 and/or edamontology/edamontology.org#10, thanks!🙏🏽
